import type { Config } from 'tailwindcss'

export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-tint": "#4d44e3",
        "secondary-container": "#39b8fd",
        "surface-dim": "#d8dadc",
        "error": "#ba1a1a",
        "surface-variant": "#e0e3e5",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#1f1ab3",
        "tertiary-fixed-dim": "#c0c1ff",
        "on-primary": "#ffffff",
        "on-background": "#191c1e",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "surface": "#f7f9fb",
        "on-secondary-fixed": "#001e2f",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-container": "#bebfff",
        "on-secondary-fixed-variant": "#004c6e",
        "on-primary-container": "#c1beff",
        "surface-container-high": "#e6e8ea",
        "secondary-fixed-dim": "#89ceff",
        "surface-container-low": "#f2f4f6",
        "secondary-fixed": "#c9e6ff",
        "outline-variant": "#c7c4d7",
        "on-primary-fixed-variant": "#3323cc",
        "error-container": "#ffdad6",
        "inverse-primary": "#c3c0ff",
        "primary-fixed": "#e2dfff",
        "on-surface": "#191c1e",
        "primary-container": "#3f33d6",
        "on-surface-variant": "#464554",
        "inverse-surface": "#2d3133",
        "on-error": "#ffffff",
        "background": "#f7f9fb",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#004666",
        "surface-container": "#eceef0",
        "primary": "#2402c1",
        "outline": "#777586",
        "tertiary-container": "#3b3bc9",
        "on-tertiary-fixed": "#07006c",
        "on-primary-fixed": "#0f0069",
        "secondary": "#006591",
        "surface-bright": "#f7f9fb",
        "primary-fixed-dim": "#c3c0ff",
        "tertiary-fixed": "#e1e0ff"
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'ai-glow': '0 8px 32px rgba(77, 68, 227, 0.05)',
        'ambient': '0 32px 64px rgba(36, 2, 193, 0.06)',
      }
    },
  },
  plugins: [],
} satisfies Config
